### ISSUE TITLE
Capital letter in imports confuses Glide package manager.

### ISSUE THREAD

**Issue by dandee** [evalphobia/logrus_sentry#40]
This package imports "github.com/Sirupsen/logrus" instead of "github.com/sirupsen/logrus". This confuses auto dependency discovery process in the [Glide](https://glide.sh/) package manager making it fail to update the project packages.

**Comment by evalphobia** [comment]
@dandee 

see 
- [case-insensitive import collision #36](https://github.com/evalphobia/logrus_sentry/issues/36) 
- [comment on Renaming upper-case 'Sirupsen' to 'sirupsen' #384](https://github.com/sirupsen/logrus/issues/451#issuecomment-264309288)

**Comment by cheshir** [comment]
Same problem here.
@evalphobia so what? sirupsen renamed back to lowercase? :)
What's the solution?

**Comment by cheshir** [comment]
Solution for glide:

```yaml
- package: github.com/Sirupsen/logrus
  repo: git@github.com:sirupsen/logrus.git
  vcs: git
  version: v0.11.x
```

But problems can occurs if another hook will import logrus package as `github.com/sirupsen/logrus`.
